name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, json

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Dump Autoload
        run: composer dump-autoload --optimize

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Cache Laravel Configuration
        run: php artisan config:cache

      - name: Cache Laravel Routes
        run: php artisan route:cache

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: 51.15.161.204
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./httpdocs/
          exclude: |
            .git*
            node_modules/
            storage/*.key
            .env
            
